name: Build Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Android app
      run: |
        cd MyCoffeeApp/MyCoffeeApp.Android
        msbuild /t:Restore
        msbuild /t:Build /p:Configuration=Release

    - name: Build iOS app
      run: |
        cd MyCoffeeApp/MyCoffeeApp.iOS
        msbuild /t:Restore
        msbuild /t:Build /p:Configuration=Release
